# version: '3'
services:
  siyuan:
    image: b3log/siyuan
    container_name: siyuan
    restart: unless-stopped
    ports:
      - "6806:6806"
    volumes:
      - /var/lib/docker/siyuan/data:/siyuan/workspace
    command: ["--accessAuthCode=CodigoSeguro"]
